/**
 * Tip güvenli hata kodları — istemci ve loglar için sabit anahtarlar.
 * @readonly
 */
const ImportErrorCodes = Object.freeze({
  INVALID_URL: "INVALID_URL",
  UNSUPPORTED_PLATFORM: "UNSUPPORTED_PLATFORM",
  PARSE_FAILED: "PARSE_FAILED",
  DUPLICATE_FOUND: "DUPLICATE_FOUND",
  IMPORT_PARTIAL: "IMPORT_PARTIAL",
  FILE_FORMAT_ERROR: "FILE_FORMAT_ERROR",
  EMPTY_FILE: "EMPTY_FILE",
  MALFORMED_PAYLOAD: "MALFORMED_PAYLOAD",
  EXTENSION_ERROR: "EXTENSION_ERROR",
  SYNC_FAILED: "SYNC_FAILED",
  STORAGE_READ_FAILED: "STORAGE_READ_FAILED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
});

module.exports = { ImportErrorCodes };
