import 'package:emlakmaster_mobile/features/consultant_daily/presentation/utils/consultant_daily_types.dart';

/// Tüm tür/ton/bayrak kombinasyonlarını kapsayan deterministik snapshot —
/// overflow / visual / live QA testlerinde paylaşılır.
ConsultantDailySnapshot dailyFixtureSnapshot() {
  ConsultantDailyEntry e({
    required String id,
    required DailyKind kind,
    required String title,
    required String typeLabel,
    required String timeLabel,
    required String detail,
    required String ctx,
    required String status,
    required DailyTone tone,
    required String actionLabel,
    required DailyActionKind actionKind,
    String? customerId,
    String? phone,
    bool needsAttention = false,
    bool isToday = false,
    bool isOverdue = false,
    bool isPriority = false,
    bool isPartial = false,
    int sortRank = 5,
  }) =>
      ConsultantDailyEntry(
        id: id,
        kind: kind,
        title: title,
        typeLabel: typeLabel,
        timeLabel: timeLabel,
        detail: detail,
        context: ctx,
        statusLabel: status,
        tone: tone,
        actionLabel: actionLabel,
        actionKind: actionKind,
        customerId: customerId,
        phone: phone,
        searchText: '$title $typeLabel $status'.toLowerCase(),
        needsAttention: needsAttention,
        isToday: isToday,
        isOverdue: isOverdue,
        isPriority: isPriority,
        isPartial: isPartial,
        sortRank: sortRank,
      );

  final entries = <ConsultantDailyEntry>[
    e(
      id: 'task:1',
      kind: DailyKind.task,
      title: 'Geciken portföy araması ve uzun başlık taşması denemesi metni',
      typeLabel: 'Görev',
      timeLabel: '3 gün gecikti',
      detail: 'Planlı görev',
      ctx: 'Kişisel görev',
      status: 'Gecikti',
      tone: DailyTone.danger,
      actionLabel: 'Görevlere git',
      actionKind: DailyActionKind.openTasks,
      needsAttention: true,
      isOverdue: true,
      isPriority: true,
      sortRank: 0,
    ),
    e(
      id: 'follow:2',
      kind: DailyKind.followUp,
      title: 'Mehmet Yılmaz Demirkol Karaköseoğlu',
      typeLabel: 'Takip',
      timeLabel: '34 gün sessiz',
      detail: 'Yeniden temas önerilir — son görüşmede fiyat itirazı vardı',
      ctx: 'Pazarlık',
      status: 'Geciken takip',
      tone: DailyTone.danger,
      actionLabel: 'Müşteriye git',
      actionKind: DailyActionKind.openCustomer,
      customerId: 'c2',
      phone: '5551112233',
      needsAttention: true,
      isOverdue: true,
      isPriority: true,
      sortRank: 1,
    ),
    e(
      id: 'cust:3',
      kind: DailyKind.customer,
      title: 'Deniz Hot Investor',
      typeLabel: 'Müşteri',
      timeLabel: 'Sıcak',
      detail: 'Yüksek ilgi · Acil takip · Randevu sinyali',
      ctx: 'Teklif',
      status: 'Sıcak',
      tone: DailyTone.danger,
      actionLabel: 'Müşteriye git',
      actionKind: DailyActionKind.openCustomer,
      customerId: 'c3',
      phone: '5559998877',
      needsAttention: true,
      isPriority: true,
      sortRank: 5,
    ),
    e(
      id: 'task:4',
      kind: DailyKind.task,
      title: 'Bugünkü daire ziyareti',
      typeLabel: 'Görev',
      timeLabel: 'Bugün',
      detail: 'Planlı görev',
      ctx: 'Müşteriye bağlı görev',
      status: 'Bugün',
      tone: DailyTone.warning,
      actionLabel: 'Müşteriye git',
      actionKind: DailyActionKind.openCustomer,
      customerId: 'c4',
      isToday: true,
      needsAttention: true,
      sortRank: 4,
    ),
    e(
      id: 'cust:5',
      kind: DailyKind.customer,
      title: 'Cem Partial Temassız',
      typeLabel: 'Müşteri',
      timeLabel: 'Temas bilgisi yok',
      detail: 'Son temas tarihi kayıtlı değil',
      ctx: 'Lead',
      status: 'Kısmi',
      tone: DailyTone.neutral,
      actionLabel: 'Müşteriye git',
      actionKind: DailyActionKind.openCustomer,
      customerId: 'c5',
      phone: '5552223344',
      isPartial: true,
      sortRank: 8,
    ),
    e(
      id: 'task:6',
      kind: DailyKind.task,
      title: 'Yaklaşan sözleşme yenileme',
      typeLabel: 'Görev',
      timeLabel: '3 gün içinde',
      detail: 'Planlı görev',
      ctx: 'Kişisel görev',
      status: 'Yaklaşan',
      tone: DailyTone.info,
      actionLabel: 'Görevlere git',
      actionKind: DailyActionKind.openTasks,
      sortRank: 7,
    ),
  ];

  return ConsultantDailySnapshot(
    entries: entries,
    summary: const ConsultantDailySummary(
      activeTasks: 3,
      overdue: 2,
      todayContacts: 4,
      hotCustomers: 1,
      customers: 12,
    ),
    greetingName: 'Ada',
    coverageNote:
        'Liste yalnızca size atanmış görev ve müşterilerden türetilir; müşteri '
        'sıcaklığı kural tabanlıdır. Performans skoru gösterilmez.',
    isEmpty: false,
  );
}

ConsultantDailySnapshot dailyEmptySnapshot() => const ConsultantDailySnapshot(
      entries: [],
      summary: ConsultantDailySummary.empty,
      greetingName: 'Ada',
      coverageNote: 'Bugün için atanmış görev veya müşteri baskısı yok.',
      isEmpty: true,
    );
